export const MODAL_OPEN_TASK = "MODAL_OPEN_TASK";
export const MODAL_OPEN_CALENDAR = "MODAL_OPEN_CALENDAR";
export const MODAL_CLOSE_TASK = "MODAL_CLOSE_TASK";
export const MODAL_CLOSE_CALENDAR = "MODAL_CLOSE_CALENDAR";
