export const MODAL_OPEN_TASK = 'MODAL_OPEN_TASK';
export const MODAL_OPEN_CALENDAR = 'MODAL_OPEN_CALENDAR';
export const MODAL_OPEN_PLANT = 'MODAL_OPEN_PLANT';
export const MODAL_OPEN_CHART = 'MODAL_OPEN_CHART';
export const MODAL_CLOSE_TASK = 'MODAL_CLOSE_TASK';
export const MODAL_CLOSE_CALENDAR = 'MODAL_CLOSE_CALENDAR';
export const MODAL_CLOSE_PLANT = 'MODAL_CLOSE_PLANT';
export const MODAL_CLOSE_CHART = 'MODAL_CLOSE_CHART';
