export const PHOTO_ADD_OBJ = 'PHOTO_ADD_OBJ';
export const PHOTO_DELETE_OBJ = 'PHOTO_DELETE_OBJ';
export const PHOTO_ADD = 'PHOTO_ADD';
export const PHOTO_ADD_SUCCESS = 'PHOTO_ADD_SUCCESS';
export const PHOTO_ADD_FAILURE = 'PHOTO_ADD_FAILURE';

export const PHOTO_DELETE = 'PHOTO_DELETE';
export const PHOTO_DELETE_SUCCESS = 'PHOTO_DELETE_SUCCESS';
export const PHOTO_DELETE_FAILURE = 'PHOTO_DELETE_FAILURE';

export const PHOTO_EDIT = 'PHOTO_EDIT';
export const PHOTO_EDIT_SUCCESS = 'PHOTO_EDIT_SUCCESS';
export const PHOTO_EDIT_FAILURE = 'PHOTO_EDIT_FAILURE';
