export const PLANT_SELECT = "PLANT_SELECT";
export const PLANT_ADD = "PLANT_ADD";
export const PLANT_ADD_SUCCESS = "PLANT_ADD_SUCCESS";
export const PLANT_ADD_FAILURE = "PLANT_ADD_FAILURE";

export const PLANT_DELETE = "PLANT_DELETE";
export const PLANT_DELETE_SUCCESS = "PLANT_DELETE_SUCCESS";
export const PLANT_DELETE_FAILURE = "PLANT_DELETE";

export const PLANT_EDIT = "PLANT_EDIT";
export const PLANT_EDIT_SUCCESS = "PLANT_EDIT_SUCCESS";
export const PLANT_EDIT_FAILURE = "PLANT_EDIT_FAILURE";
