export const REMOVE_ENABLE = "REMOVE_ENABLE";
export const REMOVE_DISABLE = "REMOVE_DISABLE";

export const REMOVE_ADD_PLANT = "REMOVE_ADD_PLANT"
export const REMOVE_DELETE_PLANT = "REMOVE_DELETE_PLANT";

export const REMOVE_ADD_TASK = "REMOVE_ADD_TASK";
export const REMOVE_DELETE_TASK = "REMOVE_DELETE_TASK";

export const REMOVE_ADD_PHOTO = "REMOVE_ADD_PHOTO";
export const REMOVE_DELETE_PHOTO = "REMOVE_DELETE_PHOTO";
