export const TASK_ADD_OBJ = "TASK_ADD_OBJ";
export const TASK_DELETE_OBJ = "TASK_DELETE_OBJ";
export const TASK_ADD = "TASK_ADD";
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS";
export const TASK_ADD_FAILURE = "TASK_ADD_FAILURE";

export const TASK_DELETE = "TASK_DELETE";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAILURE = "TASK_DELETE";

export const TASK_EDIT = "TASK_EDIT";
export const TASK_EDIT_SUCCESS = "TASK_EDIT_SUCCESS";
export const TASK_EDIT_FAILURE = "TASK_EDIT_FAILURE";
